import './globals.css'
import type { Metadata } from 'next'
import Link from "next/link"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ul className='flex'>
          <li className='mx-2'>
            <Link href="/" >Home</Link>
          </li>
          <li className='mx-2'>
            <Link href="/test" >test</Link>
          </li>
          <li className='mx-2'>
            <Link href="/test/me" >test/me</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  )
}
