

/*
 * @Author: yangchenguang
 * @Description: 
 * @Date: 2023-09-08 18:09:05
 * @LastEditors: yangchenguang
 * @LastEditTime: 2023-12-05 18:36:49
 */

import './globals.css'
import type { Metadata } from 'next'
import Link from "next/link"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ul className='flex'>
          <li className='mx-2'>
            <Link href="/" >Home</Link>
          </li>
          <li className='mx-2'>
            <Link href="/test" >test</Link>
          </li>
          <li className='mx-2'>
            <Link href="/test/me" >test/me</Link>
          </li>
          <li className='mx-2'>
            <Link href="/post/123/321" >post/123/321</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  )
}
